on:
  push:
    branches:
      - slack

name: ğŸš€ Deploy website on push
jobs:
  ftpdeploy:
    name: â¤µï¸ Checkout
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: ğŸ“¦ Get latest code
        uses: actions/checkout@v4
        with:
          ref: slack

      - name: ğŸ”¨ Build Project
        run: |
          pip install -r requirements.txt
        working-directory: projects/  # Thiáº¿t láº­p thÆ° má»¥c lÃ m viá»‡c cho step nÃ y

      - name: ğŸ‰ FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.dauden.cloud
          port: 21
          protocol: ftp
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: pyapp/slack/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            fileToExclude.txt
          working-directory: projects/  # Náº¿u FTP Deploy cáº§n thá»±c hiá»‡n tá»« thÆ° má»¥c projects
