on:
  push:
    branches:
      - slack

name: ğŸš€ Deploy website on push
jobs:
  ftpdeploy:
    name: ğŸ‰ FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“¦ Get latest code
      uses: actions/checkout@v4
      with:
        ref: 'slack'

    - name: ğŸ Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: ğŸ”¨ Build Project
      run: |
        cd projects/
        pip install -r requirements.txt
    
    - name: â¤´ï¸ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.dauden.cloud
        port: 21
        protocol: ftp
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: pyapp/slack/
        local-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt